rm -rf train
rm -rf val
rm -rf test
rm -rf tmp_*
rm -rf scenes-test.json 
rm -rf scenes-train.json
rm -rf scenes-val.json
rm -rf instructions-test.json 
rm -rf instructions-train.json
rm -rf instructions-val.json
rm -rf occlusion-cases-test.txt
rm -rf occlusion-cases-train.txt
rm -rf occlusion-cases-val.txt
